### Create Cartegory
POST http://localhost:3000/cartegory/create-cartegory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MDcxMCwiZXhwIjoxNzI0MjQyNTEwfQ.epkPjornWvOhvxerYQxyTmWru3eX8LAALvQnslMuvRY

{
  "name": "dresses"
}

### Update Cartegory
PUT http://localhost:3000/cartegory/update-cartegory/df530313-315c-462c-83f6-222971d4411d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MDcxMCwiZXhwIjoxNzI0MjQyNTEwfQ.epkPjornWvOhvxerYQxyTmWru3eX8LAALvQnslMuvRY

{
  "name": "shirts"
}

### Delete Cartegory
DELETE http://localhost:3000/cartegory/delete-cartegory/4f5c4906-badc-4181-b910-5d398c943062
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MDcxMCwiZXhwIjoxNzI0MjQyNTEwfQ.epkPjornWvOhvxerYQxyTmWru3eX8LAALvQnslMuvRY

### GetAll Cartegories
GET http://localhost:3000/cartegory/get-all-cartegories
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MDcxMCwiZXhwIjoxNzI0MjQyNTEwfQ.epkPjornWvOhvxerYQxyTmWru3eX8LAALvQnslMuvRY
