### create cart items
POST http://localhost:3000/cart/create-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyMzI3NDYsImV4cCI6MTcyNDIzNDU0Nn0.gvL0WohQw6X37kycLdeITbwKgaqr8j1PINO1Qb2hWkU

{
  "product_id": "f7e8901b-7170-42da-8d90-3469d9aae5c0",
  "item_count": 4
}

### Update cart item
POST http://localhost:3000/cart/update-cart/e6072a64-dc8e-44e4-a848-f58d50a4d421
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQxNjQ5MjUsImV4cCI6MTcyNDE2NjcyNX0.ypWVhb0yRPDQY84lAmygoX93xXkRBTqMC7nxZRBiyc4

{
  "product_id": "a8d6e477-b868-4f1f-9587-dc0af3b15d1d",
  "item_count": 1
}

### Remove item from cart
DELETE http://localhost:3000/cart/delete_item/e6072a64-dc8e-44e4-a848-f58d50a4d421
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQxNjQ5MjUsImV4cCI6MTcyNDE2NjcyNX0.ypWVhb0yRPDQY84lAmygoX93xXkRBTqMC7nxZRBiyc4

### Clear cart
DELETE http://localhost:3000/cart/clear-cart
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyMzI3NDYsImV4cCI6MTcyNDIzNDU0Nn0.gvL0WohQw6X37kycLdeITbwKgaqr8j1PINO1Qb2hWkU

### Get all cart items
GET http://localhost:3000/cart/get-cart-items
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyMzI3NDYsImV4cCI6MTcyNDIzNDU0Nn0.gvL0WohQw6X37kycLdeITbwKgaqr8j1PINO1Qb2hWkU
