### Create Order
POST http://localhost:3000/order/create-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyMzI3NDYsImV4cCI6MTcyNDIzNDU0Nn0.gvL0WohQw6X37kycLdeITbwKgaqr8j1PINO1Qb2hWkU

### Get single users' orders
GET http://localhost:3000/order/get-all-orders-by-user-id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyNDI2ODUsImV4cCI6MTcyNDI0NDQ4NX0.bMFg6kBOi8pBVKdAnnUfZn8oUaHZo-QLpZ2YHAiHQlk

### Update delivery status for one order
PUT http://localhost:3000/order/update-delivery-status/cf0a8658-1b04-4ca0-b487-14a0ef270401
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MjQxNiwiZXhwIjoxNzI0MjQ0MjE2fQ.Mx8Q6HP1EDkFT6YAqmC8lRdzwmANpKdqohtSDMN2rTI

### Update multiple delivery status
PUT http://localhost:3000/order/update-multiple-delivery-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzNjQ0MiwiZXhwIjoxNzI0MjM4MjQyfQ.jHLXChyruegR0pHTI3Ij90-O--JzQ5fOWk_GYd2SO38

{
  "order_ids": ["cf0a8658-1b04-4ca0-b487-14a0ef270401","dbd04594-f647-4cad-9904-4a5d1ec4ce3b","e1ebef36-ae0e-40d3-861c-4f7cf729306b"]
}

### Update all delivery status (Delivered)
PUT http://localhost:3000/order/update-all-delivery-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MjQxNiwiZXhwIjoxNzI0MjQ0MjE2fQ.Mx8Q6HP1EDkFT6YAqmC8lRdzwmANpKdqohtSDMN2rTI

### reset all delivery status (Pending)
PUT http://localhost:3000/order/reset-all-delivery-status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MjQxNiwiZXhwIjoxNzI0MjQ0MjE2fQ.Mx8Q6HP1EDkFT6YAqmC8lRdzwmANpKdqohtSDMN2rTI

### soft delete order by id
PUT http://localhost:3000/order/soft-delete-order/e1ebef36-ae0e-40d3-861c-4f7cf729306b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### soft delete all orders
PUT http://localhost:3000/order/soft-delete-all-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### restore single soft deleted order
PUT http://localhost:3000/order/restore-single-order/e1ebef36-ae0e-40d3-861c-4f7cf729306b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### restore all soft deleted orders
PUT http://localhost:3000/order/restore-all-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### get all soft deleted orders
GET http://localhost:3000/order/get-all-soft-deleted-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### Get all orders
GET http://localhost:3000/order/get-all-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### Get all delivered orders
GET http://localhost:3000/order/get-all-delivered-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MjQxNiwiZXhwIjoxNzI0MjQ0MjE2fQ.Mx8Q6HP1EDkFT6YAqmC8lRdzwmANpKdqohtSDMN2rTI

### Get all pending orders
GET http://localhost:3000/order/get-all-pending-orders
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc

### Delete order by order id
DELETE http://localhost:3000/order/delete-order/e1ebef36-ae0e-40d3-861c-4f7cf729306b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzODU5NSwiZXhwIjoxNzI0MjQwMzk1fQ.21zyf8HABDxnGDv7aOEb5MUCxab0b_Gf6F-9H5f4MBc
