### Create Order
POST http://localhost:3000/order/create-order
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQxNjk2MjcsImV4cCI6MTcyNDE3MTQyN30.cQnARhhGYsHsVE0tSsXFx5dPYF6UOnRsqi31Tz9aDyA

### Get single users' orders
GET http://localhost:3000/order/get-all-orders-by-user-id/8dbf4d09-fb0c-4e79-970f-5c9f79fd07da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQxNjk2MjcsImV4cCI6MTcyNDE3MTQyN30.cQnARhhGYsHsVE0tSsXFx5dPYF6UOnRsqi31Tz9aDyA
