### Create Product
POST http://localhost:3000/product/create-product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDIzMTAzNCwiZXhwIjoxNzI0MjMyODM0fQ.GJXQWn9rajuP51nJQNkKCpokZ71MszuvOYpm-pbVkiY

{
  "name": "Green African Beauty Dress",
  "images": "['africanas1.png', 'africanas2.png', 'africanas3.png']",
  "short_desc": "Official-Casual fashion",
  "long_desc": "Long sleeved new fashion for Men's look, perfect outlines, beautifull structures and manly in looks",
  "price": 3580,
  "stock_quantity": 300,
  "cartegory": "dress",
  "type": "new",
  "discount": 300,
  "max_quantity": 300
}

### Update Product
POST http://localhost:3000/product/update-product/a8d6e477-b868-4f1f-9587-dc0af3b15d1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1OTgxMywiZXhwIjoxNzI0MTYxNjEzfQ.NFDh83QmL2F1Kb_9kLkiHllGWW8ouIhQdPi2LFefZOY

{
  "name": "Africanas Mens wear",
  "images": "['africanas1.png', 'africanas2.png', 'africanas3.png']",
  "short_desc": "Official-Casual fashion",
  "long_desc": "Long sleeved new fashion for Men's look, perfect outlines, beautifull structures and manly in looks",
  "price": 2000,
  "stock_quantity": 300,
  "cartegory": "shirts",
  "type": "new",
  "discount": 150,
  "max_quantity": 250
}

### Get product by product Id
GET http://localhost:3000/product/get-product-by-id/a8d6e477-b868-4f1f-9587-dc0af3b15d1d
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MTY1NCwiZXhwIjoxNzI0MTYzNDU0fQ.4vlMMCON3Z_uNW-btdAXxGkfzWrn_t9WT7kUDdmv8-8

### Get product by product Name
GET http://localhost:3000/product/get-product-by-name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1OTgxMywiZXhwIjoxNzI0MTYxNjEzfQ.NFDh83QmL2F1Kb_9kLkiHllGWW8ouIhQdPi2LFefZOY

{
  "name": "Ankara Dress"
}

### Get product by product Cartegory
GET http://localhost:3000/product/get-product-by-cartegory
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1OTgxMywiZXhwIjoxNzI0MTYxNjEzfQ.NFDh83QmL2F1Kb_9kLkiHllGWW8ouIhQdPi2LFefZOY

{
  "cartegory": "shirts"
}

### Get all products
GET http://localhost:3000/product/get-all-products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0MjQxNiwiZXhwIjoxNzI0MjQ0MjE2fQ.Mx8Q6HP1EDkFT6YAqmC8lRdzwmANpKdqohtSDMN2rTI

{
  "cartegory": "shirts"
}

### Get all flush products
GET http://localhost:3000/product/get-flush-products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s

### Get all products on offer
GET http://localhost:3000/product/get-offered-products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s

### Set products to offers
PUT http://localhost:3000/product/set-offer-to-product/39e57bd4-922e-4035-a412-93f237efea78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MTY1NCwiZXhwIjoxNzI0MTYzNDU0fQ.4vlMMCON3Z_uNW-btdAXxGkfzWrn_t9WT7kUDdmv8-8

### Remove products from offers
PUT http://localhost:3000/product/remove-offer/39e57bd4-922e-4035-a412-93f237efea78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s

### Set product to flush
PUT http://localhost:3000/product/set-flush-product/39e57bd4-922e-4035-a412-93f237efea78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s


### Reset product from flush
PUT http://localhost:3000/product/reset-flush-product/39e57bd4-922e-4035-a412-93f237efea78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s

### Delete product
DELETE http://localhost:3000/product/delete-product/39e57bd4-922e-4035-a412-93f237efea78
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE2MzUwOSwiZXhwIjoxNzI0MTY1MzA5fQ.Kb1yDzizEI0eg-o_8L9DAgVhNqzEggoQZ3PaVSP4H0s
