### Create Review
POST http://localhost:3000/reviews/create-review/3a216f64-66d9-45a9-ad97-e318f87e8faa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyNDk5OTQsImV4cCI6MTcyNDI1MTc5NH0.paO5PblDUpBKpxFWp-oWC9zafwyXSu9GBlzvXIONR-Q

{
  "rating": 3,
  "review": "These clothe's size is amaizing, it really goes well with the shoes i also purchased here. Emma-Designs is a delight."
}

### Update Review
POST http://localhost:3000/reviews/update-review/56ef6bb6-a63e-415e-8fc6-7559c832bda6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyNDk5OTQsImV4cCI6MTcyNDI1MTc5NH0.paO5PblDUpBKpxFWp-oWC9zafwyXSu9GBlzvXIONR-Q

{
  "rating": 5,
  "review": "These clothe's size is amaizing, it really goes well with the shoes i also purchased here. Emma-Designs is a delight."
}

### Delete Review
DELETE http://localhost:3000/reviews/delete-review/56ef6bb6-a63e-415e-8fc6-7559c832bda6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0NjUwOSwiZXhwIjoxNzI0MjQ4MzA5fQ.vGmeprkbm1l3EV2ToR1sVdjEE3XNxLcRE7FubstVqZ8

### Get Review by user id
GET http://localhost:3000/reviews/get-reviews-by-user-id
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQyNDk5OTQsImV4cCI6MTcyNDI1MTc5NH0.paO5PblDUpBKpxFWp-oWC9zafwyXSu9GBlzvXIONR-Q

### Get Review by product id
GET http://localhost:3000/reviews/get-reviews-by-product-id/3a216f64-66d9-45a9-ad97-e318f87e8faa
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0ODUxOSwiZXhwIjoxNzI0MjUwMzE5fQ.eyxZuaWyPzUHhea63ENiMmWtq_gE98-LL6r2oCqiMLg

### Get Review by rating
GET http://localhost:3000/reviews/get-reviews-by-rating/4
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0ODUxOSwiZXhwIjoxNzI0MjUwMzE5fQ.eyxZuaWyPzUHhea63ENiMmWtq_gE98-LL6r2oCqiMLg

### Get All Reviews
GET http://localhost:3000/reviews/get-all-reviews
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDI0ODUxOSwiZXhwIjoxNzI0MjUwMzE5fQ.eyxZuaWyPzUHhea63ENiMmWtq_gE98-LL6r2oCqiMLg
