###Register User
POST http://localhost:3000/users/create-user
Content-Type: application/json

{
  "fullname": "Delete Me",
  "email": "deleteme23@gmail.com",
  "phone_number": "0112014055",
  "gender": "Female",
  "country": "Kenya",
  "county": "Uasin Gishu",
  "address": "ELD 910-30100",
  "profile_image": "emma.png",
  "password": "Deleteme023"
}

###Update User Details
POST http://localhost:3000/users/update-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaXMyM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NDA4MSwiZXhwIjoxNzI0MTU1ODgxfQ.pbMnYTAdHy14lTLL6cOnANXTbtiXJafl40xCvqQvl0Q

{
  "fullname": "Emmaculate Adhiambo",
  "email": "emmaculateadhiambo23@gmail.com",
  "phone_number": "0112014056",
  "gender": "Female",
  "country": "Kenya",
  "county": "Uasin Gishu",
  "address": "ELD 910-30100",
  "profile_image": "emma.png",
  "password": "Emmaculate023"
}

###Fetch All Users
GET http://localhost:3000/users/get-all-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NTk0OCwiZXhwIjoxNzI0MTU3NzQ4fQ.CZlYLLdvwlU8qYR9sD-ipfH5n8hNouqcopOnA7v72Hg

### Permanently delete single user
DELETE http://localhost:3000/users/delete-user/b7e25fba-8744-4e75-921e-7b995a0747f6
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaXMyM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NDA4MSwiZXhwIjoxNzI0MTU1ODgxfQ.pbMnYTAdHy14lTLL6cOnANXTbtiXJafl40xCvqQvl0Q

### soft delete single user
PUT http://localhost:3000/users/soft-delete-user/8dbf4d09-fb0c-4e79-970f-5c9f79fd07da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NTk0OCwiZXhwIjoxNzI0MTU3NzQ4fQ.CZlYLLdvwlU8qYR9sD-ipfH5n8hNouqcopOnA7v72Hg

### Get all soft deleted users
GET http://localhost:3000/users/get-all-soft-deleted-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaXMyM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NDA4MSwiZXhwIjoxNzI0MTU1ODgxfQ.pbMnYTAdHy14lTLL6cOnANXTbtiXJafl40xCvqQvl0Q

### Get single User
GET http://localhost:3000/users/get-single-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOGRiZjRkMDktZmIwYy00ZTc5LTk3MGYtNWM5Zjc5ZmQwN2RhIiwiZnVsbG5hbWUiOiJGZWxpeCBPa290aCIsImVtYWlsIjoiZmVsaXhva290aDA3OEBnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwNzY4MDMwNDc4IiwiZ2VuZGVyIjoiTWFsZSIsImNvdW50cnkiOiJLZW55YSIsImNvdW50eSI6IlVhc2luIEdpc2h1IiwiYWRkcmVzcyI6IkVMRCA5MTAtMzAxMDAiLCJwcm9maWxlX2ltYWdlIjoibXlfaW1hZ2UucG5nIiwicGFzc3dvcmQiOiIkMmIkMDgkUVJlTm1RSEFKM0JubFlaUmMxZDhULjYxcXZvLmdJeGlmNXdvR291RFdBdU9JM1hWRXpNcDIiLCJyb2xlIjoidXNlciIsImNyZWF0ZWRBdCI6IjIwMjQtMDgtMjBUMDA6MDA6MDAuMDAwWiIsImlzV2VsY29tZWQiOmZhbHNlLCJpc0RlbGV0ZWQiOmZhbHNlLCJpYXQiOjE3MjQxNjk2MjcsImV4cCI6MTcyNDE3MTQyN30.cQnARhhGYsHsVE0tSsXFx5dPYF6UOnRsqi31Tz9aDyA

### Get single User By Name
GET http://localhost:3000/users/get-user-by-name
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaXMyM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NDA4MSwiZXhwIjoxNzI0MTU1ODgxfQ.pbMnYTAdHy14lTLL6cOnANXTbtiXJafl40xCvqQvl0Q

{
  "fullname": "Delete Me"
}

### Get single User By email
GET http://localhost:3000/users/get-user-by-email
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NTk0OCwiZXhwIjoxNzI0MTU3NzQ4fQ.CZlYLLdvwlU8qYR9sD-ipfH5n8hNouqcopOnA7v72Hg

{
  "email": "felixokoth078@gmail.com"
}

### Retrieve deleted user
PUT http://localhost:3000/users/retrieve-deleted-user/8dbf4d09-fb0c-4e79-970f-5c9f79fd07da
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NTk0OCwiZXhwIjoxNzI0MTU3NzQ4fQ.CZlYLLdvwlU8qYR9sD-ipfH5n8hNouqcopOnA7v72Hg

### Retrieve all deleted users
PUT http://localhost:3000/users/retrieve-deleted-users
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiOTc2OWJlYTctNmZkYS00YmIyLTk0MzYtYzg0YjE2YzEwYzUzIiwiZnVsbG5hbWUiOiJFbW1hY3VsYXRlIEFkaGlhbWJvIiwiZW1haWwiOiJlbW1hY3VsYXRlYWRoaWFtYm8yM0BnbWFpbC5jb20iLCJwaG9uZV9udW1iZXIiOiIwMTEyMDE0MDU2IiwiZ2VuZGVyIjoiRmVtYWxlIiwiY291bnRyeSI6IktlbnlhIiwiY291bnR5IjoiVWFzaW4gR2lzaHUiLCJhZGRyZXNzIjoiRUxEIDkxMC0zMDEwMCIsInByb2ZpbGVfaW1hZ2UiOiJlbW1hLnBuZyIsInBhc3N3b3JkIjoiJDJiJDA4JENZYmYva0lhU3RUUTRubXl4RHJlWnViS0MwY01Cd1Z3TVFFb2dPelh0Si5pdmw5UEFVcUlHIiwicm9sZSI6ImFkbWluIiwiY3JlYXRlZEF0IjoiMjAyNC0wOC0yMFQwMDowMDowMC4wMDBaIiwiaXNXZWxjb21lZCI6ZmFsc2UsImlzRGVsZXRlZCI6ZmFsc2UsImlhdCI6MTcyNDE1NTk0OCwiZXhwIjoxNzI0MTU3NzQ4fQ.CZlYLLdvwlU8qYR9sD-ipfH5n8hNouqcopOnA7v72Hg
